spring:
  profiles:
    active:
      dev-postgresql
      #dev-mariadb
      #dev-h2
  jpa:
    show-sql: false
---

spring:
  profiles: dev-h2
  h2:
    console:
      enabled: true

---

spring:
  profiles: dev-mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/autentia?serverTimezone=UTC
    username: misrra
    password: misrra
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  profiles: dev-postgresql
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/autentia
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
